### ISSUE TITLE
Missing required module 'CNIOAtomics' on Xcode 11.6 - iOS

### ISSUE THREAD

**Issue by PPacie** [swift-aws/aws-sdk-swift#338]
**Describe the bug**
It doesn't compile if you import any modules outside of the main app target. 

**To Reproduce** (See Test project)
1. You need to have an Xcode iOS project with at least 1 extra framework (target) apart from the app one.
2. Add `aws-sdk-swift` via SPM. 
3. Import any of the modules (e.g: `import S3`) in any files of one of your internal frameworks. 
4. Try to build. 
5. An error message will be displayed: `Missing required module 'CNIOAtomics' .

**Expected behavior**
Build normally.

**Setup (please complete the following information):**
- OS: iOS
- Version of aws-sdk-swift: 4.7.0
- Xcode 11.6

**Additional context** Example Project.
[TestProject.zip](https://github.com/swift-aws/aws-sdk-swift/files/4962498/TestProject.zip)

Thank you very much in advance.

**Comment by adam-fowler** [comment]
I'm not sure how you got to the point where Xcode was linking. When I load your sample project the `URLExtension.swift` file doesn't even compile, returning error `No such module 'S3'`.

The example project you provided has aws-sdk-swift added to the TestProject target. The Networking target has no knowledge of the dependency. You need to add aws-sdk-swift to the Networking target. 

Go to the Networking target in the project settings, and add an entry to Frameworks and Libraries list. When you click on the plus sign you should get a list of all the aws-sdk-swift libs, select S3. Once you have done that remove the S3 library from TestTarget.

**Comment by PPacie** [comment]
Hi Adam,

Thanks for the quick response. Really appreciated.

The `No such module 'S3'` error is not the one expected. I think you might need to do a `Clean` + `Build` and `Reset Package Caches` from `File > Swift Packages` first.

However adding the `aws-sdk-swift` to the main target is the whole point of the issue. It doesn't compile using it in other modules and I believe it should. It displays the `Missing required module 'CNIOAtomics' ` error. 

I am working on a project which contains other SPM Libraries on the main app Target and those can be normally imported and used in the rest of the targets. 

This was the expected behavior for `aws-sdk-swift`as well.

I am attaching another example project where you can see a SPM dependency added to the main target and imported in another Module of the app.

[TestProjectSPM2.zip](https://github.com/swift-aws/aws-sdk-swift/files/4964629/TestProjectSPM2.zip)

PS: I understand your point too and that was my approach before (adding the `aws-sdk-swift` to the target I needed, `Networking` in this example project). However, by doing that, I lose the possibility of using it outside that module and it has other issues with the CIs, etc.

**Comment by adam-fowler** [comment]
This looks like an issue with Xcode. There have been similar issues in the past. One version of this can be found here #167. I added an issue in the swift-nio repo https://github.com/apple/swift-nio/issues/1128. There is a related bug in https://bugs.swift.org can't find it at the moment. As that one was resolved I think it has been deleted. The issue is related to Swift packages that contain submodules used to expose C libraries to the parent Swift module. You could ask the guys on the https://swiftpm.slack.com about this. Here is an invite https://join.slack.com/t/swiftpm/shared_invite/zt-eaeo7sva-wYNA70fUKxOHCGAezjUIEw.

Regarding getting this working without a fix for Xcode, if you add S3 to the Networking module it appears to be available in the TestProject target. And if you want to add it to other modules you can do that through the "Framework and Libraries" list in the project settings. 

How does this affect your CI?

Another solution would be to make everything a SPM package except the main executable target and include them all through the Xcode Swift package interface. That should resolve everything.

**Comment by adam-fowler** [comment]
Although I have just verified the adding via "Framework and Libraries" doesnt work. You get duplication of library code errors.

If you want to use aws-sdk-swift across multiple modules those modules will all have to be SPM packages

sorry

**Comment by PPacie** [comment]
Thanks again for your response. 

Before opening the issue I went over most of those related issues as well. However, none of those seemed to be exactly the same, nor the work arounds worked this time. Thanks for pointing out.

Regarding the work arounds:
- If you add it to the `Networking` module, you can get it working in the rest of the modules (I was wrong before). You don't need to re-add it again in "Framework and Libraries" as you will get that duplication code errors.
This was current setup before trying to add `aws-sdk-swift` to the main app target.
This approach works well on local  but it does't goes through `xcodebuild -resolvePackageDependencies` when running the CI on the server. I get:
 ```xcodebuild: error: Could not resolve package dependencies:
  An unknown error occurred``` 

- I thought about making the `Networking` module a SPM package but I think that can delay the development a little bit. Will see 👍 .

I agree with you that it looks more like an Xcode/SPM issue and not an `aws-sdk-swift` one. We can close this issue. Thank you very much again for your time and insights.
